### ISSUE TITLE
runtime errors in kunstmusik/libsyi/tests/gate.csd - perf-pass statements illegal 

### ISSUE THREAD

**Issue by ceberman** [kunstmusik/libsyi#1]
Hi, first of all, this looks fantastic, and i hope this is the right place to report this issue.  I get the following errors when running gate.csd.      I'm wondering if i should experiment with moving these into the instrument definitions.

The version is: --Csound version 6.09.1 (double samples) Jul 10 2017 

Thanks very much in advance

...
instr synth uses instrument number 8
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_measure)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (set_pattern_seq)
error:  perf-pass statements illegal in header blk (copy_pattern_seq)
Elapsed time at end of orchestra compile: real: 0.023s, CPU: 0.023s
...

**Comment by kunstmusik** [comment]
I haven't looked at or used this code in a while, but the test file works
here in latest Csound from Git (essentially 6.10 beta).  I made a change to
the code to put most of the initialization code into an Init instr, then
called it with schedule.  Could you pull the latest and try it there?

**Comment by ceberman** [comment]
Thanks very much 

Will do

**Comment by ceberman** [comment]
Hello again, and thank you for such a quick response!!

I thought I'd report that on 6.09, it looks like the error messages don't actually have an effect on execution;  perhaps they are really only warnings.   I found i could get rid of the error messages by putting the statements into instruments, and the execution result was the same.   

I will work with my test version for a while, as i am using Rory Walsh's Unity Csound, and it is likely it is bundled with an older version of Csound

**Comment by kunstmusik** [comment]
I'm going to close out this issue then since it works fine from within instruments.  (And the test gate.csd is working without warnings here.)
